version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lingo_flow_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-lingoflow}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lingo_network

  redis:
    image: redis:5-alpine3.11
    container_name: lingo_flow_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - lingo_network

networks:
  lingo_network:
    driver: bridge

volumes:
  postgres_data:
